from ecosys.__xgui import *
from ecosys.__ocx import *
from abc import *

class aUi:...

class aSplashScreen:...
class aLoginScreen(ABC):
    __slots__ = ["pushButton","lineEdit"]
    def __init__(self):
        self.pushButton:Button = None
        self.lineEdit:Edit = None
class aConfigorScreen:...
class aOperatorScreen:...
class aReviewScreen:...

class aInspectInterface:...
class aMachineInterface:...
class aReportInterface:...
class aScrewInterface:...
class aConfigorInterface:...
class aOperatorInterface:...
